import type { Metadata, Viewport } from "next";
import { IBM_Plex_Mono, Archivo } from "next/font/google";
import "./styles/globals.scss";

/* §3 substitutes: display/UI → IBM Plex Mono (for GT Pressura),
   body/h2 → Archivo (for Monument Grotesk).

   Note on metrics: GT Pressura Mono is unusually narrow (~0.5em
   advance), which is what lets §3's literal 245rem carry a 13-character
   line inside the 110% overture frame. Plex is 0.6em and Martian Mono —
   the other named free substitute — is 0.70em, so both overflow at the
   literal size. --mono-fit in _tokens.scss corrects for that; see there. */
const mono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  variable: "--font-mono"
});

const body = Archivo({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  variable: "--font-body"
});

/* Tab titles: the page first, the name last. A tab truncates from the right,
   so the word that tells two tabs apart has to lead; "· Frank Fu" follows
   when there is room. Sub-pages give only their own name (the template adds
   the rest); the homepage and the invite paths, which set no title, get the
   default. */
const description =
  "Frank Fu works at both ends of the same job: scoping a fuzzy problem, finding what is causing it, then building the thing that fixes it — and measuring whether people keep using it.";

/* Link previews (LinkedIn, Slack, iMessage) read Open Graph tags from the raw
   HTML, never from what the client renders — so they live here, and the card
   images are 1200×630 (LinkedIn's 1.91:1): the homepage's is a drawn comic
   panel in public/og/home.jpg, the rest are generated by app/og. */
export const metadata: Metadata = {
  metadataBase: new URL("https://frankfu.me"),
  title: { default: "Frank Fu · Data & Product", template: "%s · Frank Fu" },
  description,
  openGraph: {
    type: "website",
    siteName: "Frank Fu",
    url: "/",
    title: "Frank Fu · Data & Product",
    description,
    images: [{ url: "/og/home.jpg", width: 1200, height: 630, alt: "Comic panel: Frank dives past reaching hands for the ball, shouting “I’ll make it for sure!”" }]
  },
  twitter: { card: "summary_large_image" }
};

export const viewport: Viewport = {
  themeColor: "#F5F3EC"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${mono.variable} ${body.variable}`} data-touch="false">
      <body>{children}</body>
    </html>
  );
}
